const baseAlertSummaries = [
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'SB-ML',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-10T00:49:25Z',
    severity: 0.98,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'US-CA',
    colName: 'KPMD',
    type: 'Freshness',
    occurredAt: '2023-02-09T18:16:11Z',
    severity: 0.15,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'US-AK',
    colName: 'DCK',
    type: 'Freshness',
    occurredAt: '2023-02-15T12:41:43Z',
    severity: 0.0,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'US-TX',
    colName: 'KGRK',
    type: 'Nullness',
    occurredAt: '2023-02-15T20:50:51Z',
    severity: 0.13,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'US-WA',
    colName: 'KBVS',
    type: 'Freshness',
    occurredAt: '2023-02-10T16:29:01Z',
    severity: 0.86,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'PF-U-A',
    colName: null,
    type: 'Nullness',
    occurredAt: '2023-02-09T02:09:55Z',
    severity: 0.95,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'BR-RO',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-11T23:34:45Z',
    severity: 0.81,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'GB-SCT',
    colName: 'EGPW',
    type: 'Cardinality',
    occurredAt: '2023-02-11T23:20:55Z',
    severity: 0.31,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'ID-PA',
    colName: 'WABI',
    type: 'Distribution',
    occurredAt: '2023-02-16T14:22:09Z',
    severity: 0.97,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'SR-SI',
    colName: 'SMDO',
    type: 'Distribution',
    occurredAt: '2023-02-14T00:16:19Z',
    severity: 0.44,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'BJ-AK',
    colName: 'DBBN',
    type: 'Cardinality',
    occurredAt: '2023-02-13T07:26:55Z',
    severity: 0.07,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'SN-DK',
    colName: null,
    type: 'Freshness',
    occurredAt: '2023-02-09T09:58:32Z',
    severity: 0.27,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'PF-U-A',
    colName: null,
    type: 'Nullness',
    occurredAt: '2023-02-16T06:33:00Z',
    severity: 0.21,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'TL-OE',
    colName: null,
    type: 'Freshness',
    occurredAt: '2023-02-13T23:54:25Z',
    severity: 0.9,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'IR-23',
    colName: 'OIZJ',
    type: 'Distribution',
    occurredAt: '2023-02-09T17:14:34Z',
    severity: 0.7,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'PG-HE',
    colName: null,
    type: 'Freshness',
    occurredAt: '2023-02-08T12:18:19Z',
    severity: 0.49,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'SO-TO',
    colName: 'HCMV',
    type: 'Distribution',
    occurredAt: '2023-02-16T14:47:19Z',
    severity: 0.71,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'PK-SD',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-11T07:12:12Z',
    severity: 0.78,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'US-MI',
    colName: null,
    type: 'Freshness',
    occurredAt: '2023-02-12T03:05:05Z',
    severity: 0.86,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'AU-QLD',
    colName: null,
    type: 'Nullness',
    occurredAt: '2023-02-10T11:31:59Z',
    severity: 0.22,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'SB-RB',
    colName: 'AGGB',
    type: 'Nullness',
    occurredAt: '2023-02-12T10:32:03Z',
    severity: 0.49,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'US-TX',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-16T13:37:37Z',
    severity: 0.06,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'BR-AM',
    colName: null,
    type: 'Freshness',
    occurredAt: '2023-02-07T10:26:48Z',
    severity: 0.38,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'FR-L',
    colName: null,
    type: 'Nullness',
    occurredAt: '2023-02-15T13:22:40Z',
    severity: 0.84,
  },
  {
    relationName: 'SALES.SALES_DM.V_DAILY_RATE_SHEET',
    matName: 'DK-82',
    colName: null,
    type: 'Nullness',
    occurredAt: '2023-02-12T18:55:42Z',
    severity: 0.69,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'CN-44',
    colName: null,
    type: 'Freshness',
    occurredAt: '2023-02-14T01:01:38Z',
    severity: 0.9,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'SE-BD',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-13T14:31:22Z',
    severity: 0.79,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'BR-RS',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-16T22:01:42Z',
    severity: 0.82,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'BR-PR',
    colName: null,
    type: 'Freshness',
    occurredAt: '2023-02-08T12:31:16Z',
    severity: 0.68,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'AU-QLD',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-13T22:32:15Z',
    severity: 0.59,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'CM-OU',
    colName: null,
    type: 'Cardinality',
    occurredAt: '2023-02-14T17:10:13Z',
    severity: 0.95,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'TH-47',
    colName: null,
    type: 'Cardinality',
    occurredAt: '2023-02-16T20:40:30Z',
    severity: 0.25,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'CA-NT',
    colName: 'CJL8',
    type: 'Cardinality',
    occurredAt: '2023-02-08T06:42:16Z',
    severity: 0.58,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'US-WI',
    colName: null,
    type: 'Cardinality',
    occurredAt: '2023-02-11T16:22:57Z',
    severity: 0.86,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'MX-GUA',
    colName: 'MMLO',
    type: 'Nullness',
    occurredAt: '2023-02-10T07:34:44Z',
    severity: 0.47,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'US-KS',
    colName: 'KGBD',
    type: 'Distribution',
    occurredAt: '2023-02-10T18:44:20Z',
    severity: 0.67,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'CA-ON',
    colName: 'CYFH',
    type: 'Nullness',
    occurredAt: '2023-02-15T22:23:19Z',
    severity: 0.88,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'MX-TAM',
    colName: null,
    type: 'Cardinality',
    occurredAt: '2023-02-16T23:27:35Z',
    severity: 0.15,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'US-AK',
    colName: null,
    type: 'Cardinality',
    occurredAt: '2023-02-11T13:10:23Z',
    severity: 0.35,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'US-WI',
    colName: 'KGTG',
    type: 'Distribution',
    occurredAt: '2023-02-11T18:51:41Z',
    severity: 0.16,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'IE-G',
    colName: null,
    type: 'Freshness',
    occurredAt: '2023-02-14T23:23:34Z',
    severity: 0.64,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'CA-QC',
    colName: 'CYGR',
    type: 'Nullness',
    occurredAt: '2023-02-08T18:48:04Z',
    severity: 0.87,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'PG-WPD',
    colName: null,
    type: 'Freshness',
    occurredAt: '2023-02-12T18:19:25Z',
    severity: 0.41,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'EG-ALX',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-16T01:28:08Z',
    severity: 0.84,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'TR-47',
    colName: 'LTCR',
    type: 'Freshness',
    occurredAt: '2023-02-11T04:46:30Z',
    severity: 0.02,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'US-UT',
    colName: 'KBDG',
    type: 'Distribution',
    occurredAt: '2023-02-07T12:49:52Z',
    severity: 0.96,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'PH-LEY',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-11T07:24:44Z',
    severity: 0.55,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'SL-W',
    colName: 'GFHA',
    type: 'Cardinality',
    occurredAt: '2023-02-13T04:04:52Z',
    severity: 0.27,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'CA-SK',
    colName: 'CZFD',
    type: 'Freshness',
    occurredAt: '2023-02-12T20:19:59Z',
    severity: 0.95,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'RU-KHM',
    colName: null,
    type: 'Cardinality',
    occurredAt: '2023-02-11T21:51:40Z',
    severity: 0.13,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'US-GA',
    colName: null,
    type: 'Freshness',
    occurredAt: '2023-02-09T02:02:58Z',
    severity: 0.92,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'PG-MPL',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-14T12:03:25Z',
    severity: 0.01,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'CO-VID',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-07T03:15:40Z',
    severity: 0.48,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'BR-SE',
    colName: 'SNOP',
    type: 'Freshness',
    occurredAt: '2023-02-11T08:07:23Z',
    severity: 0.87,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'US-AK',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-15T16:57:52Z',
    severity: 0.38,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'KR-11',
    colName: 'RKSS',
    type: 'Cardinality',
    occurredAt: '2023-02-11T04:16:38Z',
    severity: 0.84,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'AF-NIM',
    colName: 'OAZJ',
    type: 'Distribution',
    occurredAt: '2023-02-11T20:07:57Z',
    severity: 0.7,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'BR-SC',
    colName: null,
    type: 'Freshness',
    occurredAt: '2023-02-07T17:56:41Z',
    severity: 0.46,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'CA-BC',
    colName: null,
    type: 'Nullness',
    occurredAt: '2023-02-15T20:49:08Z',
    severity: 0.69,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'US-PA',
    colName: null,
    type: 'Cardinality',
    occurredAt: '2023-02-08T06:05:04Z',
    severity: 0.2,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'DZ-19',
    colName: 'DAAS',
    type: 'Cardinality',
    occurredAt: '2023-02-08T19:18:48Z',
    severity: 0.5,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'US-AK',
    colName: null,
    type: 'Cardinality',
    occurredAt: '2023-02-13T06:55:24Z',
    severity: 0.48,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'IR-06',
    colName: 'OIBI',
    type: 'Distribution',
    occurredAt: '2023-02-12T14:15:11Z',
    severity: 0.74,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'NO-17',
    colName: 'ENRM',
    type: 'Nullness',
    occurredAt: '2023-02-09T19:57:56Z',
    severity: 0.47,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'US-TX',
    colName: null,
    type: 'Freshness',
    occurredAt: '2023-02-08T11:52:40Z',
    severity: 0.31,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'AU-QLD',
    colName: 'YMWX',
    type: 'Distribution',
    occurredAt: '2023-02-16T11:43:21Z',
    severity: 0.3,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'IN-KL',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-11T01:01:37Z',
    severity: 0.82,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'GN-N',
    colName: 'GUMA',
    type: 'Distribution',
    occurredAt: '2023-02-16T11:18:48Z',
    severity: 0.67,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'CA-ON',
    colName: 'CYKF',
    type: 'Freshness',
    occurredAt: '2023-02-08T06:56:09Z',
    severity: 0.29,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'BO-S',
    colName: 'SLAS',
    type: 'Distribution',
    occurredAt: '2023-02-10T21:56:09Z',
    severity: 0.98,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'SA-01',
    colName: 'OERK',
    type: 'Freshness',
    occurredAt: '2023-02-15T18:01:05Z',
    severity: 0.85,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'US-NY',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-16T06:17:34Z',
    severity: 0.32,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'BR-AM',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-15T07:22:46Z',
    severity: 0.47,
  },
  {
    relationName: 'SALES.SALES_DM.DAILY_REVENUE_CUM',
    matName: 'SE-BD',
    colName: 'ESUP',
    type: 'Distribution',
    occurredAt: '2023-02-08T21:17:01Z',
    severity: 0.05,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'DZ-27',
    colName: 'DA14',
    type: 'Distribution',
    occurredAt: '2023-02-07T21:00:26Z',
    severity: 0.22,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'US-HI',
    colName: 'PHJR',
    type: 'Distribution',
    occurredAt: '2023-02-07T01:04:53Z',
    severity: 0.14,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'PT-13',
    colName: 'LPPR',
    type: 'Nullness',
    occurredAt: '2023-02-08T05:12:50Z',
    severity: 0.83,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'PF-U-A',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-08T15:10:29Z',
    severity: 0.02,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'PT-20',
    colName: 'LPCR',
    type: 'Freshness',
    occurredAt: '2023-02-11T15:26:48Z',
    severity: 0.61,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'CN-23',
    colName: 'ZYDQ',
    type: 'Nullness',
    occurredAt: '2023-02-07T16:24:30Z',
    severity: 0.8,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'GA-2',
    colName: 'FOON',
    type: 'Distribution',
    occurredAt: '2023-02-13T11:37:01Z',
    severity: 0.66,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'CA-NU',
    colName: 'CYXP',
    type: 'Freshness',
    occurredAt: '2023-02-15T01:02:48Z',
    severity: 0.58,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'US-MO',
    colName: 'KCGI',
    type: 'Freshness',
    occurredAt: '2023-02-15T19:39:06Z',
    severity: 0.94,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'LS-J',
    colName: null,
    type: 'Freshness',
    occurredAt: '2023-02-08T17:40:58Z',
    severity: 0.65,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'US-OK',
    colName: 'KFDR',
    type: 'Distribution',
    occurredAt: '2023-02-07T14:07:35Z',
    severity: 0.91,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'BS-GT',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-11T12:43:06Z',
    severity: 0.4,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'TH-42',
    colName: 'VTUL',
    type: 'Cardinality',
    occurredAt: '2023-02-12T12:40:03Z',
    severity: 0.63,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'AU-WA',
    colName: null,
    type: 'Freshness',
    occurredAt: '2023-02-11T10:02:22Z',
    severity: 0.22,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'BG-26',
    colName: null,
    type: 'Cardinality',
    occurredAt: '2023-02-12T11:20:27Z',
    severity: 0.08,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'US-NH',
    colName: 'KAFN',
    type: 'Freshness',
    occurredAt: '2023-02-12T15:09:05Z',
    severity: 0.07,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'FR-E',
    colName: 'LFRV',
    type: 'Freshness',
    occurredAt: '2023-02-12T22:04:42Z',
    severity: 0.77,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'CO-PUT',
    colName: 'SKVG',
    type: 'Freshness',
    occurredAt: '2023-02-07T08:27:48Z',
    severity: 0.65,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'PG-WPD',
    colName: null,
    type: 'Distribution',
    occurredAt: '2023-02-09T15:25:57Z',
    severity: 0.52,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'MZ-N',
    colName: 'FQLU',
    type: 'Cardinality',
    occurredAt: '2023-02-13T15:45:10Z',
    severity: 0.3,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'BR-RO',
    colName: 'SBJI',
    type: 'Freshness',
    occurredAt: '2023-02-16T11:06:35Z',
    severity: 0.95,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'NZ-MWT',
    colName: null,
    type: 'Freshness',
    occurredAt: '2023-02-14T15:41:05Z',
    severity: 0.98,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'US-TX',
    colName: 'KAUS',
    type: 'Distribution',
    occurredAt: '2023-02-16T12:17:03Z',
    severity: 0.05,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'BS-LI',
    colName: 'MYLS',
    type: 'Distribution',
    occurredAt: '2023-02-10T20:24:11Z',
    severity: 0.86,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'HN-FM',
    colName: 'MHTG',
    type: 'Freshness',
    occurredAt: '2023-02-13T12:39:30Z',
    severity: 0.5,
  },
  {
    relationName:
      'MARKETING.SOCIAL_MEDIA.MONTHLY_SOCIAL_MEDIA_CAMPAIGN_SUCCESS_RATE',
    matName: 'AU-QLD',
    colName: 'YNMN',
    type: 'Distribution',
    occurredAt: '2023-02-15T03:01:40Z',
    severity: 0.01,
  },
];

export default baseAlertSummaries;
